[book]
title = "Net Nook"
authors = ["Kymdon13"]
description = "A collection of notes and resources in learning and building."
language = "en"
multilingual = false

[build]
create-missing = false

[output.html]
git-repository-url = "https://kymdon13.github.io/"
mathjax-support = true
# the order here does not matter
additional-js = [
    # init.js must be first
    "js/init.js",
    "js/editor.js",
    # highlight language support
    "js/all-languages.min.js", # BUG the style goes wrong the same as bash.min.js
    # mermaid
    "js/mermaid-init.js",
    "js/mermaid.min.js",
    # ace and its modes
    "js/ace.js",
    "js/mode-c_cpp.js",
    "js/mode-rust.js",
    "js/ext-language_tools.js", # autocompletion extension
]
theme = "theme"

[output.html.search]
limit-results = 7
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.code]
# A prefix string per language (one or more chars).
# Any line starting with `prefix+space` is hidden.
hidelines = { cpp = "~ " }

[output.html.playground]
editable = true
line-numbers = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
